### ISSUE TITLE
Made an attempt to install on a Mac with Homebrew

### ISSUE THREAD

**Issue by TyrfingMjolnir** [TheAppgineer/roon-tui#1]
<img width="1920" alt="image" src="https://github.com/TheAppgineer/roon-tui/assets/4602183/16efb505-4460-4629-aa71-9aaed7583527">

How I did this is in the README.md in my fork of this project.

```
sood connection for unique_id: 6238871b-570f-44d5-acc6-100dee1c0dfc
                                                                   sood connection for unique_id: 2979bdca-e2b1-4dd5-a2c5-6af24c88e103
                                                                                                                                      thread 'tokio-runtime-worker' panicked at 'index out of bounds: the len is 1 but the index is 2', /Users/user/.cargo/git/checkouts/rust-roon-api-f2f474c008eedc12/f3f96f4/src/lib.rs:319:56
                                                 note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
                                                                                                                              thread 'tokio-runtime-worker' panicked at 'called `Result::unwrap()` on an `Err` value: SendError { .. }', /Users/user/.cargo/git/checkouts/rust-roon-api-f2f474c008eedc12/f3f96f4/src/lib.rs:276:67
                                                  channel closed
                                                                channel closed
                                                                              channel closed
                                                                                            channel closed
```

**Comment by JanKoudijs** [comment]
Can you test again with [version 0.0.2](https://github.com/TheAppgineer/roon-tui/releases/tag/0.0.2)?

**Comment by JanKoudijs** [comment]
Closing this issues as I had no further reports of it.
